apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadsrgz5267-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadsrgz5267-tenant-component
    app.kubernetes.io/part-of: loadsrgz5267-tenant-app
  name: loadsrgz5267-tenant-component
  namespace: loadsrgz5267-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadsrgz5267-tenant-component
    weight: null
status: {}
